// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2itrofeWczmj66fcFTCFTdeFMTYHdMxA',
    appId: '1:875108140422:web:ab8a326dd90a999629d807',
    messagingSenderId: '875108140422',
    projectId: 'analyst-f98ab',
    authDomain: 'analyst-f98ab.firebaseapp.com',
    storageBucket: 'analyst-f98ab.firebasestorage.app',
    measurementId: 'G-V06VQE0VNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbpZNdgIUb17_OJWD13TjdO4W0Dmab91A',
    appId: '1:875108140422:android:2f673ecc2b3b39be29d807',
    messagingSenderId: '875108140422',
    projectId: 'analyst-f98ab',
    storageBucket: 'analyst-f98ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkK2b9lydSCZwe2bsdN7wjMo7_YZJ1450',
    appId: '1:875108140422:ios:f4924a7d3b2c901329d807',
    messagingSenderId: '875108140422',
    projectId: 'analyst-f98ab',
    storageBucket: 'analyst-f98ab.firebasestorage.app',
    iosBundleId: 'com.example.decisionSpin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkK2b9lydSCZwe2bsdN7wjMo7_YZJ1450',
    appId: '1:875108140422:ios:f4924a7d3b2c901329d807',
    messagingSenderId: '875108140422',
    projectId: 'analyst-f98ab',
    storageBucket: 'analyst-f98ab.firebasestorage.app',
    iosBundleId: 'com.example.decisionSpin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2itrofeWczmj66fcFTCFTdeFMTYHdMxA',
    appId: '1:875108140422:web:e74fd6b97ff5878f29d807',
    messagingSenderId: '875108140422',
    projectId: 'analyst-f98ab',
    authDomain: 'analyst-f98ab.firebaseapp.com',
    storageBucket: 'analyst-f98ab.firebasestorage.app',
    measurementId: 'G-E78RPHKQ7C',
  );
}
